### ISSUE TITLE
fallo al cargar recurso a través de URI.

### ISSUE THREAD

**Issue by miermontoto** [pugafran/controldiabet.es#1]
![image](https://github.com/pugafran/controldiabet.es/assets/20926603/16dc5037-36c4-43d9-98a3-8fe6c34897f8)

el error provoca que no se escanee ningún código.

**Comment by pugafran** [comment]
Eso se debe a que no estás ejecutando la página como un servidor local, en el código se hace uso de fetch para acceder a alimentos.json mediante http por tanto al ejecutarlo sin servidor no va a funcionar.
